version: '2'
services:

  ### Postgres container
  postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - /srv/docker/postgresql:/var/lib/postgresql
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=twittarablespringboot
            - POSTGRES_USER=twittarable