version: '2'
services:

  ### Postgres container
  mysql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - /srv/docker/postgresql:/var/lib/postgresql
        environment:
            - DB_PASS=root
            - DB_NAME=twittarablespringboot
            - DB_USER=twittarable
            - MYSQL_PASSWORD=root